-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS ROLES_PERMISSIONS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ROLE_ID INT NOT NULL,
    PERMISSION_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE,
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE
);
-- +goose StatementEnd

-- +goose StatementBegin
INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 1, ID FROM PERMISSIONS;
-- +goose StatementEnd

-- +goose StatementBegin
INSERT INTO ROLES_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 2, ID FROM PERMISSIONS WHERE NAME IN ("user:read");
-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS ROLES_PERMISSIONS;
-- +goose StatementEnd
